# This workflow use the Divio API to deploy into the Test Environment on a push to develop branch event

name: Divio Continuous Deployment

# Setting environment variables of the secret keys for easy access
env:
  API_TOKEN: ${{ secrets.API_TOKEN }}
  TEST_ENVIRONMENT_ID: ${{ secrets.TEST_ENVIRONMENT_ID }}  
  LIVE_ENVIRONMENT_ID: ${{ secrets.LIVE_ENVIRONMENT_ID }}

on:
  push:
    branches: [ develop ]

# jobs run sequentially or in parallel to execute the workflow
jobs:

# This workflow contains a single job called "deploy"
 deploy:

  # The type of runner that this job will run on
  runs-on: ubuntu-latest
  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
  # Checks-out the repository under $GITHUB_WORKSPACE, so this job can access it
  - uses: actions/checkout@v2

  # Push to develop branch triggers deployment to the TEST environment
  - name: Deploy to the Test environment
    run: |
     # To deploy to TEST
     curl -X POST --data "environment=$TEST_ENVIRONMENT_ID" --header "Authorization: Token $API_TOKEN" https://api.divio.com/apps/v3/deployments/
